# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Switch', max_length=50)),
                ('timeframe', models.PositiveIntegerField()),
                ('notification', models.PositiveIntegerField()),
                ('beneficiary', models.EmailField(max_length=254)),
                ('secret', models.TextField(blank=True, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Controller')),
            ],
        ),
    ]
