# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_auto_20170731_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='dayspassed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='notification',
            field=models.IntegerField(default=20),
        ),
    ]
