# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_auto_20170803_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='dayspassed',
        ),
        migrations.AddField(
            model_name='controller',
            name='last_seen',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
