# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_auto_20170913_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='notification',
            field=models.IntegerField(),
        ),
    ]
