# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_auto_20170913_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='beneficiary',
            field=models.EmailField(default='merlin.buczek@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switch',
            name='name',
            field=models.CharField(default='New Switch', max_length=50),
        ),
        migrations.AddField(
            model_name='switch',
            name='secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
