# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_auto_20170913_1436'),
        ('dms', '0006_auto_20170913_1535'),
    ]

    operations = [
    ]
